# Generated by Django 3.1 on 2020-09-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('imagen', models.ImageField(blank=True, default='/default.png', null=True, upload_to='')),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_post', models.DateTimeField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('0', ''), ('1', 'Carton'), ('2', 'Vidrio'), ('3', 'Madera'), ('4', 'Escombros'), ('5', 'Metal'), ('6', 'Baterias'), ('7', 'Desechos Electronicos'), ('8', 'Bombillas de Luz')], default='0', max_length=1)),
                ('peso_aprox', models.SmallIntegerField(default='0')),
                ('unidad', models.CharField(choices=[('0', ''), ('1', 'g'), ('2', 'Kg'), ('3', 'Tn')], default='0', max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.ciudad')),
            ],
        ),
    ]
