# Generated by Django 3.1 on 2020-09-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='codigo',
            new_name='id',
        ),
    ]
