# Generated by Django 3.1 on 2020-09-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20200921_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_post',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
